### ISSUE TITLE
Do you have a working example?

### ISSUE THREAD

**Issue by allenhwkim** [boundlessgeo/ol-mapbox-style#17]
First, thanks for this module.

Do you have any working example page using plunker, jsfiddle, or any?

I am an author of [react-openlayers](https://github.com/allenhwkim/react-openlayers), and tried to implement with  ol.layer.VectorTile with MapBox style json object.

Currently, I am trying to achieve [this](https://github.com/openmaptiles/www.openmaptiles.org/blob/master/maps/ol.js) with the current version of olms, but not successful yet.

Ref. https://github.com/allenhwkim/react-openlayers/issues/2
https://rawgit.com/allenhwkim/react-openlayers/master/app/index.html#/layers/vector-tile-2
![image](https://cloud.githubusercontent.com/assets/1437734/24085657/1489ffe6-0cd6-11e7-9c8c-82a4754130f3.png)

**Comment by ahocevar** [comment]
I just tried your example at https://rawgit.com/openmaptiles/www.openmaptiles.org/master/maps/ol.html, and it seems to work fine for me.

The official example of ol-mapbox-style is [here](https://github.com/boundlessgeo/ol-mapbox-style/tree/master/example), with a hosted version [here](https://rawgit.com/boundlessgeo/ol-mapbox-style/master/example/index.html).

**Comment by hankypanky666** [comment]
I have a similar problem with angular 2 app(

**Comment by allenhwkim** [comment]
[The working one](https://rawgit.com/openmaptiles/www.openmaptiles.org/master/maps/ol.html) is using this `olms.js`
https://github.com/openmaptiles/www.openmaptiles.org/blob/master/maps/olms.js
and this repo. has `index.js`
https://github.com/boundlessgeo/ol-mapbox-style/blob/master/index.js

Where is this `olms.js` coming from?

The current package.json is pointing to `index.js`

```
  "main": "index.js",
```

When I import like the following, it comes from `index.js`, not `dist/olms.js`. Am I right?

```
import { apply } from 'ol-mapbox-style';
```

**Comment by ahocevar** [comment]
You are right. olms.js is a standalone build for use without a bundler. When you use a bundler, you do not need it. And actually the recommended use is with a bundler.

See https://github.com/boundlessgeo/ol-mapbox-style/blob/master/test/test.js for a typical app that uses a bundler.

mapbox-to-ol-style has a lower level API and less dependencies. You can use it when you just style a single layer and do not need automatic font and sprite loading.

All that said, I still do not get from the comments on this ticket what the actual problem is. The stack trace in the first comment indicates a problem with OpenLayers. Maybe you are using an OpenLayers version that is too old?

**Comment by hankypanky666** [comment]
`
  public drawMap(): void {
    this.map = new Map({loadTilesWhileAnimating: true, loadTilesWhileInteracting: true, pixelRatio: 1, controls: []});

    this.view = new View({
      projection: 'EPSG:3857',
      center: proj.transform(this.centerCoords, 'EPSG:4326', 'EPSG:3857'),
      zoom: this.zoom,
      extent: this.bounds,
      maxZoom: this.maxZoom,
      minZoom: this.minZoom
    });

    //this.view.on('change:resolution', this.constrainPan.bind(this));
    //this.view.on('change:center', this.constrainPan.bind(this));

    //map events Observable
    this.map.on('pointermove', (event: MapBrowserEvent) => this.onPonterMove.next(event));
    this.map.on('moveend', (event: MapEvent) => this.onMoveEnd.next(event));
    this.map.on('singleclick', (event: MapBrowserEvent) => this.onSingleClick.next(event));
    this.map.on('click', (event: MapBrowserEvent) => this.onClick.next(event));

    //this.createLayers();
    this.map.setView(this.view);
    this.map.setTarget(this.mapEl);
    this.map.addControl(new control.ScaleLine());
    let mousePosition = new control.MousePosition({projection: 'EPSG:4326', className: 'mouse-position'});
    mousePosition.setCoordinateFormat((coord) => coordinate.format(coord, 'Координаты курсора: {y}, {x}', 6));
    this.map.addControl(mousePosition);


    let tileGrid = tilegrid.createXYZ({tileSize: 512, maxZoom: 22});

    let lay = new layer.VectorTile({
      source: new source.VectorTile({
        projection: '',
        format: new format.MVT(),
        tileGrid: tileGrid,
        tilePixelRatio: 8,
        url: 'http://localhost:8080/data/v3/{z}/{x}/{y}.pbf'
      })
    });

    //this.map.addLayer(lay);

    this.http.get('http://localhost:8080/styles/osm-bright.json')
      .map(res => res.json())
      .subscribe(res => {
        applyStyle(lay, res, 'openmaptiles').then(() => {
          this.map.addLayer(lay);
        })
      });
  }
`
with openlayers 4.0.1

**Comment by ahocevar** [comment]
@hankypanky666 Your snippet does not give me any clue. Can you put up a live example, e.g. with a CodePan, that shows the issue?

**Comment by metazool** [comment]
I've also encountered this issue when trying to use ol-mapbox-style on an OpenLayers VectorTile source in a React app. It doesn't occur when using the standalone olms.js. 

Here's a tiny project based on create-react-app that reproduces the issue as simply as I can, throwing errors similar to that reported by the OP:
https://github.com/metazool/ol-vectortile-react 

```
Uncaught TypeError: c.Y is not a function
    at Mt (:3000/static/js/bundle.js:73642)
```

The frustrating part is that when I switch from ol.js to ol-debug.js (by changing the line in _node_modules/openlayers/package.json_ to read `"browser": "dist/ol-debug.js",`) to try to get an insight into what OL is doing, then **the tile layer just starts working** with no changes to the code and no errors in the console!

I've had no trouble with the standalone build. This is all the latest release as of writing - OL ^4.2.0, ol-mapbox-style ^2.4.0, React ^15.6.1. I appreciate the issue may not even belong to this repo but this is the only place i've seen discussion of it.

**Comment by ahocevar** [comment]
I have published an update yesterday, and we now also pull in ol ^4.2.0. Maybe this fixes your issue?

**Comment by metazool** [comment]
Thank you for the update @ahocevar 

I've updated to 2.5.1 but unfortunately still see the problem occurring - _ol.js:617 Uncaught TypeError: c.Y is not a function_ etc etc

Suspicion is the problem may lie with webpack, I can look harder into this side of things but it's a bit beyond my JS ken ;)

**Comment by ahocevar** [comment]
@metazool: Looks like you're using the wrong OpenLayers package in your app. Use `ol`, not `openlayers`.

**Comment by metazool** [comment]
OK brilliant, when I switch to the ES6 'ol' npm package then this works well! I've updated my toy example repo accordingly.

Thanks very much for your help.

**Comment by ahocevar** [comment]
@allenhwkim, you'll also have to switch from the `openlayers` npm package to the `ol` package.
